apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-frontend
  template:
    metadata:
      labels:
        app: auto-frontend
    spec:
      containers:
        - name: auto-frontend
          image: bhanureddy1906/auto-frontend:e40226e857d35e5faae4b8d545160767fce7360a
          ports:
            - containerPort: 80
