apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-frontend
  template:
    metadata:
      labels:
        app: auto-frontend
    spec:
      containers:
        - name: auto-frontend
          image: bhanureddy1906/auto-frontend:a63d5e6a7dbdebf898b716006b9e0cf292efe03c
          ports:
            - containerPort: 80
