apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-frontend
  template:
    metadata:
      labels:
        app: auto-frontend
    spec:
      containers:
        - name: auto-frontend
          image: bhanureddy1906/auto-frontend:c065f1c12fc43be1fd7d18bcee1053afe3d4c4b9
          ports:
            - containerPort: 80
